service: handam-serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

functions:
  app:
    handler: lambda.handler
    events:
    - http: ANY /
    - http: 'ANY {proxy+}'
