service: handam-serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  app:
    handler: lambda.handler
    events:
    - http: ANY /
    - http: 'ANY {proxy+}'
